openapi: "3.0.1"
info:
  title: Customer service API
  description: API to managment products of bank
  version: 1.0.0
servers:
  - url: http://localhost:8383
    description: local server
paths:
  /api/products:
    get:
      summary: Getting products.
      operationId: findAll
      responses:
        '200':
          description: Success find all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductResponse"
    post:
      summary: Create new product of bank.
      operationId: createProduct
      requestBody:
        description: Details to create new product of bank.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        '200':
          description: Success create
          content:
            application/json:
              schema:
                type: string
  /api/products/{productId}:
    get:
      summary: Updated product
      operationId: getProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        '404':
          description: Product not found
    put:
      summary: Updated product
      operationId: udpate
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details to updated product.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: Success updated
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Product not found to updated

    delete:
      summary: delete product
      operationId: delete
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful deleted
        '404':
          description: Product not found to delete
  /api/products/{productId}/holders:
    get:
      summary: Gettting holders by productId
      operationId: getHolderByProductId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AdditionalPersonBean"
        '404':
          description: Product not found
    put:
      summary: Update holders by productId
      operationId: updateHolderByProductId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details to updated product.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdditionalPersonBean"
      responses:
        '200':
          description: Success updated
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Product not found to updated

  /api/products/{productId}/auths:
    get:
      summary: Gettting holders by productId
      operationId: getSignaturesAuthByProductId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AdditionalPersonBean"
        '404':
          description: Product not found
    put:
      summary: Update holders by productId
      operationId: updateSignaturesAuthByProductId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details to updated product.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdditionalPersonBean"
      responses:
        '200':
          description: Success updated
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Product not found to updated

components:
  schemas:
    ProductRequest:
      type: object
      properties:
        productType:
          type: string
        familyProduct:
          type: string
        userBank:
          type: string
        customer:
          $ref: "#/components/schemas/CustomerBean"
        activeProduct:
          $ref: "#/components/schemas/ActiveProductBean"
        passiveProduct:
          $ref: "#/components/schemas/PassiveProductBean"
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/AdditionalPersonBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/AdditionalPersonBean'
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          description: unique ID
        productType:
          type: string
        status:
          type: string
        family:
          type: string
        createdDate:
          type: string
          format: date-time
        customer:
          $ref: "#/components/schemas/CustomerBean"
        activeProduct:
          $ref: "#/components/schemas/ActiveProductBean"
        passiveProduct:
          $ref: "#/components/schemas/PassiveProductBean"
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/AdditionalPersonBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/AdditionalPersonBean'
    ActiveProductBean:
      type: object
      properties:
        hasCreditCard:
          type: boolean
        creditLimit:
          type: number
          format: double
        creditLimitEnabled:
          type: number
          format: double
        creditLimitUsed:
          type: number
          format: double

    PassiveProductBean:
      type: object
      properties:
        isFreeCommission:
          type: boolean
        amountOfOpen:
          type: number
          format: double
        accountNumber:
          type: string
        inforToTransaction:
          $ref: "#/components/schemas/InfoTransactionBean"

    AdditionalPersonBean:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        phone:
          type: string
        identification:
          $ref: "#/components/schemas/IdentificationBean"

    CustomerBean:
      type: object
      properties:
        customerId:
          type: string
        customerType:
          type: string
    IdentificationBean:
      type: object
      properties:
        typeIdentification:
          type: string
        numberIdentification:
          type: string
    InfoTransactionBean:
      type: object
      properties:
        commission:
          type: number
          format: double
        maxPerMonth:
          type: string
        transactionDone:
          type: string
        enabledToMovement:
          type: boolean
