openapi: "3.0.1"
info:
  title: Customer service API
  description: API to managment products of bank
  version: 1.0.0
servers:
  - url: http://localhost:8383
    description: local server
paths:
  /api/products:
    get:
      summary: Getting products.
      operationId: findAll
      responses:
        '200':
          description: Success find all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductResponse"
    post:
      summary: Create new product of bank.
      operationId: createProduct
      requestBody:
        description: Details to create new product of bank.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        '200':
          description: Success create
          content:
            application/json:
              schema:
                type: string
  /api/products/{productId}:
    put:
      summary: Updated product
      operationId: udpate
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details to updated product.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductRequest"
      responses:
        '200':
          description: Success updated
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Product not found to updated

    delete:
      summary: delete product
      operationId: delete
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful deleted
        '404':
          description: Product not found to delete



components:
  schemas:
    ProductRequest:
      type: object
      properties:
        id:
          type: string
          description: unique ID
        customerId:
          type: string
          description: Customer Id
        customerType:
          type: string
        productType:
          type: string
          description: type of product
        userBank:
          type: string
          description: username of bank who is managmenting this product
        holders:
          type: array
          description: List of holders
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
        authorizedSignatories:
          type: array
          description: List of signatures auth
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'

    ProductResponse:
      type: object
      properties:
        id:
          type: string
          description: unique ID
        customerId:
          type: string
          description: Customer Id
        Products:
          type: array
          description: List of products associated with this product
          items:
            $ref: "#/components/schemas/ProductBean"




    ActiveProductBean:
      type: object
      properties:
        id:
          type:  string
          description: active product's id
        accountNumber:
          type: string
        status:
          type: string
        hasCreditCard:
          type: boolean
        creditLimit:
          type: number
          format: double
        creditLimitEnabled:
          type: number
          format: double
        creditLimitUsed:
          type: number
          format: double
        productType:
          type: string
        createdDate:
          type: string
          format: date-time
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'

    PassiveProductBean:
      type: object
      properties:
        id:
          type:  string
          description: active product's id
        accountNumber:
          type: string
        status:
          type: string
        commissionMovement:
          type: number
          format: double
        isFreeCommission:
          type: boolean
        maxMovementPerMonth:
          type: integer
          format: int64
        productType:
          type: string
        createdDate:
          type: string
          format: date-time
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'

    PersonalInformationAddBean:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        identification:
          type: string
        typeIdentification:
          type: string
        email:
          type: string
        phone:
          type: string

    UpdateProductRequest:
      type: object
      properties:
        id:
          type:  string
        accountNumber:
          type: string
        action:
          type: string
        productType:
          type: string
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
    DeleteProductRequest:
      type: object
      properties:
        id:
          type:  string
        accountNumber:
          type: string
        action:
          type: string

    ProductBean:
      type: object
      properties:
        accountNumber:
          type: string
        productType:
          type: string
        status:
          type: string
        family:
          type: string
        holders:
          type: array
          description: List of holders associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
        authorizedSignatories:
          type: array
          description: List of signatories authorized associated with this product
          items:
            $ref: '#/components/schemas/PersonalInformationAddBean'
